# Server Configuration
server.port=8080

# DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/skins_schema?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:(y6x2N;Z@1H=}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP Configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Exposed Configuration
spring.exposed.show-sql=false
spring.exposed.generate-ddl=true

# Jackson Configuration
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null
